export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const BASKET_ROUTE = '/basket'
export const DRESS_ROUTE = '/dress'
export const SHOP_ROUTE = '/shop'
export const REGISTRATION_ROUTE = '/registration'